# Generated by Django 5.1.4 on 2025-05-02 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='last_otp_sent',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
