# Generated by Django 5.1.4 on 2025-05-07 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autapp', '0002_myuser_last_otp_sent'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='Active_Game',
            field=models.BooleanField(default=False),
        ),
    ]
