# Generated by Django 5.0.7 on 2024-12-31 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autapp', '0002_game'),
    ]

    operations = [
        migrations.RenameField(
            model_name='game',
            old_name='game_id',
            new_name='game_type',
        ),
        migrations.AlterField(
            model_name='game',
            name='channel_name',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='myuser',
            name='token',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
