# Generated by Django 5.1.4 on 2025-01-23 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autapp', '0003_rename_game_id_game_game_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='ballance',
            field=models.IntegerField(default=0),
        ),
    ]
