# Generated by Django 5.1.4 on 2025-05-24 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autapp', '0003_myuser_active_game'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='last_otp_fp',
            field=models.DateField(blank=True, null=True),
        ),
    ]
