# Generated by Django 5.1.4 on 2025-05-26 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autapp', '0004_myuser_last_otp_fp'),
    ]

    operations = [
        migrations.CreateModel(
            name='chiweProfit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gameType', models.CharField(max_length=10)),
                ('profit', models.DecimalField(decimal_places=3, default=0.0, max_digits=100)),
            ],
        ),
    ]
