# Generated by Django 5.1.4 on 2025-01-25 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autapp', '0004_game_ballance'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='ballance',
            field=models.IntegerField(default=0),
        ),
        migrations.DeleteModel(
            name='game',
        ),
    ]
