# Generated by Django 5.1.4 on 2025-01-26 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autapp', '0005_myuser_ballance_delete_game'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='ballance',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
