# Generated by Django 5.1.4 on 2025-05-29 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autapp', '0005_chiweprofit'),
    ]

    operations = [
        migrations.CreateModel(
            name='Maintainance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enabled', models.BooleanField(default=False)),
                ('message', models.TextField(blank=True, default='We are under maintenance. Please check back later.')),
            ],
        ),
    ]
