# Generated by Django 5.1.4 on 2025-05-29 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autapp', '0006_maintainance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maintainance',
            name='enabled',
            field=models.BooleanField(default=True),
        ),
    ]
