# Generated by Django 5.1.4 on 2025-05-30 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autapp', '0007_alter_maintainance_enabled'),
    ]

    operations = [
        migrations.AddField(
            model_name='chiweprofit',
            name='sum',
            field=models.DecimalField(decimal_places=3, default=0.0, max_digits=100),
        ),
    ]
