# Generated by Django 5.1.4 on 2025-01-28 12:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('autapp', '0007_profile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
