# Generated by Django 5.1.4 on 2025-01-28 12:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autapp', '0008_delete_profile'),
    ]

    operations = [
        migrations.CreateModel(
            name='game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Total_Game', models.IntegerField(default=0)),
                ('Win_Game', models.IntegerField(default=0)),
                ('Lose_Game', models.IntegerField(default=0)),
                ('TotalWinings', models.IntegerField(default=0)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
