# Generated by Django 5.1.4 on 2025-02-17 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autapp', '0010_remove_myuser_ballance_ballance'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='logged_in',
            field=models.BooleanField(default=False),
        ),
    ]
