# Generated by Django 5.1.4 on 2025-02-17 18:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('autapp', '0011_myuser_logged_in'),
    ]

    operations = [
        migrations.RenameField(
            model_name='myuser',
            old_name='logged_in',
            new_name='is_logged_in',
        ),
    ]
