# Generated by Django 5.1.4 on 2025-02-18 17:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autapp', '0012_rename_logged_in_myuser_is_logged_in'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='points',
            field=models.IntegerField(default=0),
        ),
        migrations.CreateModel(
            name='GameHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_created=True)),
                ('Bet_amount', models.BooleanField(default=0.0)),
                ('GameType', models.CharField(max_length=10)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
