# Generated by Django 5.1.4 on 2025-02-20 13:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('autapp', '0013_myuser_points_gamehistory'),
    ]

    operations = [
        migrations.DeleteModel(
            name='game',
        ),
    ]
