# Generated by Django 5.1.4 on 2025-02-20 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autapp', '0014_delete_game'),
    ]

    operations = [
        migrations.AddField(
            model_name='gamehistory',
            name='TotalEarning',
            field=models.DecimalField(decimal_places=3, default=0.0, max_digits=100),
        ),
        migrations.AddField(
            model_name='gamehistory',
            name='TotalPlayed',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='gamehistory',
            name='TotalWin',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='gamehistory',
            name='Totaloss',
            field=models.IntegerField(default=0),
        ),
    ]
