# Generated by Django 5.1.4 on 2025-02-20 15:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('autapp', '0015_gamehistory_totalearning_gamehistory_totalplayed_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gamehistory',
            name='date',
        ),
    ]
