# Generated by Django 5.1.4 on 2025-02-21 12:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autapp', '0016_remove_gamehistory_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gamehistory',
            name='Bet_amount',
        ),
        migrations.RemoveField(
            model_name='gamehistory',
            name='GameType',
        ),
        migrations.CreateModel(
            name='InGame',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Bet_amount', models.BooleanField(default=0.0)),
                ('GameType', models.CharField(max_length=10)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
