# Generated by Django 5.1.4 on 2025-02-21 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autapp', '0017_remove_gamehistory_bet_amount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingame',
            name='win',
            field=models.BooleanField(default=False),
        ),
    ]
