# Generated by Django 5.1.4 on 2025-02-21 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autapp', '0018_ingame_win'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingame',
            name='DateOfGame',
            field=models.DateField(auto_created=True, null=True),
        ),
    ]
