# Generated by Django 5.1.4 on 2025-02-21 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autapp', '0019_ingame_dateofgame'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ingame',
            old_name='win',
            new_name='Win',
        ),
        migrations.AlterField(
            model_name='ingame',
            name='Bet_amount',
            field=models.DecimalField(decimal_places=3, default=0.0, max_digits=100),
        ),
        migrations.AlterField(
            model_name='ingame',
            name='DateOfGame',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
