# Generated by Django 5.1.4 on 2025-02-21 13:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autapp', '0020_rename_win_ingame_win_alter_ingame_bet_amount_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingame',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
