# Generated by Django 5.1.4 on 2025-04-25 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autapp', '0022_myuser_pendingdeposit_myuser_pendingwithdrwal_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='forgetPasswordToken',
            field=models.IntegerField(null=True),
        ),
    ]
