# Generated by Django 5.1.4 on 2025-03-16 13:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('monitary', '0002_withdrawalrequest_requestedat'),
    ]

    operations = [
        migrations.RenameField(
            model_name='withdrawalrequest',
            old_name='date',
            new_name='ResponseTime',
        ),
    ]
