# Generated by Django 5.1.4 on 2025-03-30 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitary', '0004_depositrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='depositrequest',
            name='SenderName',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
