# Generated by Django 5.1.4 on 2025-04-23 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitary', '0005_depositrequest_sendername'),
    ]

    operations = [
        migrations.CreateModel(
            name='TelebirrReq',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=20, null=True)),
                ('tx_id', models.CharField(max_length=10)),
                ('amount', models.IntegerField()),
                ('date', models.DateTimeField()),
                ('completed', models.BooleanField(default=False)),
            ],
        ),
        migrations.RemoveField(
            model_name='depositrequest',
            name='ScreenShot',
        ),
    ]
