# Generated by Django 5.1.4 on 2025-04-23 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitary', '0006_telebirrreq_remove_depositrequest_screenshot'),
    ]

    operations = [
        migrations.AlterField(
            model_name='telebirrreq',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
