# Generated by Django 5.1.4 on 2025-04-23 20:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('monitary', '0007_alter_telebirrreq_amount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='telebirrreq',
            name='date',
        ),
    ]
