# Generated by Django 5.1.4 on 2025-04-23 20:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('monitary', '0008_remove_telebirrreq_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='depositrequest',
            old_name='phone_number',
            new_name='tx_id',
        ),
    ]
